### ISSUE TITLE
Home Assistant重启后的状态不一致会导致无法控制浴霸开关

### ISSUE THREAD

**Issue by keniji** [liuzhe1947/homeassistant_zinguo_mqtt#1]
当某个开关是打开的状态时，如果重启HA，则HA中该开关状态会（重置）显示为关闭。然后因为状态不一致，会导致HA无法控制该开关的情况出现。

**Comment by liuzhe1947** [comment]
感谢您的反馈，双击即可切换状态，这个BUG在日后的改进中更新，请关注。

**Comment by keniji** [comment]
> 感谢您的反馈，双击即可切换状态，这个BUG在日后的改进中更新，请关注。

另外关于这个问题的出现，是因为有一天我发现浴霸风暖在家里没人时突然自己打开了，然后现在每天都会出现浴霸某个开关不定时自己触发的现象，不知道是解除不良还是因为别的原因。而且在平时使用时，会发现温度显示的数码管会经常闪动，就像是电压不稳或者接触不良一样，请问你这边有遇到过这种情况吗？
